# Generated by Django 2.1.4 on 2020-04-21 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('acompanhante', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoPeriodoEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoTrajeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passagens', models.IntegerField()),
                ('aluno_codigo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaTrajeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscolaEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Empresa')),
                ('escola_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Escola')),
            ],
        ),
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('codigo_mes', models.AutoField(primary_key=True, serialize=False)),
                ('desdricao', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nivel_ensino_cod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.NivelEnsino')),
            ],
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('distancia', models.FloatField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('cod_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidade_cod_destino', to='blog.Localidade')),
                ('cod_saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidade_cod_saida', to='blog.Localidade')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_escola', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Escola')),
                ('codigo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='empresatrajeto',
            name='trajeto_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Trajeto'),
        ),
        migrations.AddField(
            model_name='alunotrajeto',
            name='dt_mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Periodo'),
        ),
        migrations.AddField(
            model_name='alunotrajeto',
            name='trajeto_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Trajeto'),
        ),
        migrations.AddField(
            model_name='alunoperiodoescola',
            name='empresa_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Empresa'),
        ),
        migrations.AddField(
            model_name='alunoperiodoescola',
            name='periodo_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Periodo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='escola_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Escola'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='serie_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Serie'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='trajeto_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Trajeto'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turno_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Turno'),
        ),
    ]
