# Generated by Django 2.2.12 on 2020-04-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escola',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='escola',
            name='telefone',
            field=models.CharField(max_length=255),
        ),
    ]
