# Generated by Django 2.1.4 on 2020-04-21 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajeto',
            name='cod_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.Empresa'),
            preserve_default=False,
        ),
    ]
