# Generated by Django 2.1.4 on 2020-04-24 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_trajeto_cod_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='trajeto_codigo',
        ),
    ]
