# Generated by Django 2.2.12 on 2020-04-04 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidade',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trajeto',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('distancia', models.FloatField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('cod_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidade_cod_destino', to='blog.Localidade')),
                ('cod_saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidade_cod_saida', to='blog.Localidade')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='escola',
            name='id',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='nome',
        ),
        migrations.AddField(
            model_name='escola',
            name='codigo',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
