# Generated by Django 2.2.12 on 2020-04-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200404_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
