# Generated by Django 2.2.12 on 2020-04-04 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_empresa_nivelensino_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('acompanhante', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('escola_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Escola')),
                ('serie_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Serie')),
                ('trajeto_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Trajeto')),
                ('turno_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Turno')),
            ],
        ),
    ]
