# Generated by Django 2.2.12 on 2020-04-17 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_aluno_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('mes', models.CharField(max_length=255)),
                ('desdricao', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
