# Generated by Django 2.2.12 on 2020-04-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodo',
            old_name='codigo',
            new_name='codigo_mes',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='mes',
        ),
    ]
