# Generated by Django 2.2.12 on 2020-04-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alunoperiodoescola_alunotrajeto_empresatrajeto_escolaempresa_usuarioescola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioescola',
            name='cod_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escola_codigo', to='blog.Localidade'),
        ),
    ]
