# Generated by Django 2.2.12 on 2020-04-18 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200418_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioescola',
            name='cod_escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Escola'),
        ),
    ]
